name: ETAS Scheduler Test

on:
  schedule:
    - cron: "7,17,27,37,47,57 * * * *"

  workflow_dispatch:

jobs:
  scheduler-test:
    runs-on: ubuntu-latest

    steps:
      - name: Show trigger information
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Schedule: ${{ github.event.schedule }}"
          echo "Repository: ${{ github.repository }}"
          echo "Ref: ${{ github.ref }}"
          echo "UTC:"
          date -u
